name: Simba

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git php composer
      
    - name: Set up Node.js 18.12.0
      uses: actions/setup-node@v2
      with:
        node-version: '18.12.0'
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
        aws-region: eu-west-2

    - name: Install Frontend dependencies
      run: |
        npm install -g yarn
        yarn
    
    - name: Build Frontend Code
      run: yarn build

    - name: Build Backend Code
      run: composer install --prefer-dist

    - name: Deploy Laravel code
      env:
          PRIVATE_KEY: ${{ secrets.AWS_PEM_KEY  }}
          HOSTNAME : ${{ secrets.HOSTNAME  }}
          USER_NAME : ${{ secrets.USER_NAME  }}
          ENV : ${{ secrets.ENV  }}
      run: |
        echo "$ENV" > .env
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        rsync -r --exclude 'node_modules' --exclude 'storage'  --exclude '.git/' --delete-after -e "ssh -o StrictHostKeyChecking=no -i private_key" . ${USER_NAME}@${HOSTNAME}:/var/www/nxgeninventors.com/simba/

        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /var/www/nxgeninventors.com/simba/ && 
            sudo chmod -R 777 storage && 
            php artisan storage:link 
        '
        
        
